### ISSUE TITLE
.log and .trees files are too large

### ISSUE THREAD

**Issue by ViralExanthemata** [Taming-the-BEAST/Taming-the-BEAST-Website-spare#1]
Hello,
I ran BEAST 5 times with MCMC 100,000,000 (store every -1) and saved every 1000th log file and 1000th trees file. A few of my ESS values are barely getting to 200.
Now that I want to combine the log and use the trees files in densitree, they are far too big.
I have tried to run them through LogCombiner, with re-sampling at lower frequency, but so far it was futile.
If I would happen to save every 10,000th file, would I loose important information?
Please comment.

**Comment by laduplessis** [comment]
Hi Helene, 

Please only post issues specific to the website https://taming-the-beast.github.io here. For general questions about using BEAST please use https://groups.google.com/forum/#!forum/beast-users For general issues with BEAST2 please use https://github.com/CompEvol/beast2/issues

10,000 samples should be enough to get a good estimate of the posterior, so logging every 10,000 steps should be ok with a chain of 100,000,000. You should still be able to resample your files at a lower frequency with LogCombiner (so you don't need to rerun). It may be that Java is not allocating enough memory to LogCombiner to complete the resampling. 

Best regards,
Louis
